services:
  nextjs-app:
    build: .
    restart: always
    ports:
      - "${NEXT_PUBLIC_PORT}:${NEXT_PUBLIC_PORT}"
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: ${NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}
      NEXT_PUBLIC_PORT: ${NEXT_PUBLIC_PORT}
    volumes:
      - .:/app
    command: npm run dev
